Added a new service for receiving messages
However it broke the toasts. We need to fix those. Error is:
ClassCastException: cannot be cast to android.app.Activity